version: "3.8"

services:
  reactionbot:
    image: bananaztech/reactionbot:latest
    container_name: reactionbot-df-prod
    restart: always
    environment:
      DB_PORT: 3306
      DB_HOST: "example.com"
      DB_USER: "Key-API"
      DB_PWD: "example"
      DB_NAME: "keys"

networks:
  default:
    external:
      name: bots